### ISSUE TITLE
repo content?

### ISSUE THREAD

**Issue by iv2985** [yerfor/MimicTalk#1]
Hi, nice work on the paper. Do you guys plan to publish the code to github?

**Comment by yerfor** [comment]
Hi, we are polishing the code right now. Maybe released in 2 or 3 days. Thanks for your attention.

**Comment by TheMindExpansionNetwork** [comment]
Ohhhhhhhhh sooooooooo exited thank you

**Comment by rahulmanuwas** [comment]
looking forward to testing the code - it looks promising!

**Comment by stormcenter** [comment]
nice work

**Comment by yerfor** [comment]
Due to the ethic review policy in bytedance, the code release time may be postponed for few days. Thanks for your patience.

**Comment by yerfor** [comment]
The code is released. And I'm closing the issue.

**Comment by jpgallegoar** [comment]
Thank you! Can't wait to test it out
