### ISSUE TITLE
效果不尽如人意

### ISSUE THREAD

**Issue by YLongJin** [yerfor/MimicTalk#13]
https://github.com/user-attachments/assets/1bcf3c66-5e39-4f4d-a8cf-decc340d9014

按readme的流程操作的，请问怎么能达到论文的效果

**Comment by yuys0602** [comment]
这也太差了吧

**Comment by shirubei** [comment]
怀疑他们训练的视频都是国外的，估计得重新拿中文视频来重新训练

**Comment by zRich** [comment]
@YLongJin 你的环境是什么样的？我按照文档安装在windowsy和wsl上都跑不起来

**Comment by 11898d** [comment]
![image](https://github.com/user-attachments/assets/7ba0356a-2896-4d43-b0c7-00ceb7f75ba5)


> @YLongJin 你的环境是什么样的？我按照文档安装在windowsy和wsl上都跑不起来

要求好像要A100或者V100

**Comment by wangaocheng** [comment]
4090能跑，windows用docker训练没有什么问题。还在测试中，代码bug挺多的。

**Comment by wyton2020** [comment]
你要么别拿出来开源,一堆bug, 还有 requirements.txt 也没有,钓鱼也不是这么钓,太差了!!!!
app_mimictalk.py启动之后,文件上传不了,太垃圾了!

**Comment by alexhmyang** [comment]
我运行 这个 都没任何 反应啊，windows
![image](https://github.com/user-attachments/assets/060247a9-d08f-487e-aa32-c5e5b6ddc766)

**Comment by YMMF007** [comment]
> 7510_1729734802.mp4 
> 按readme的流程操作的，请问怎么能达到论文的效果

您好，请问您是怎么替换的人物呀，有进行训练吗
