### ISSUE TITLE
free(): invalid pointer

### ISSUE THREAD

**Issue by jupinter** [yerfor/MimicTalk#17]
Great work!
But when I tried to run python  inference/train_mimictalk_on_a_video.py using data/raw/examples/German_20s.mp4,
I got the error: "free(): invalid pointer".
Have you got any idea about it. Thanks!

**Comment by Hugo-san** [comment]
Hi, I also met this error. Can you please tell me how you solved it?

**Comment by Hugo-san** [comment]
Hi, I met this problem too, can you please tell me how you solved it? Thanks!
